Vcon 4 conversation window
Toad-Labs/vc-frontend-static pull request #3
Opened 2021-06-08 18:53 UTC by nibivi77

### [Conversation Window](https://decdvirtualconcierge.atlassian.net/jira/software/projects/VCON/boards/2?selectedIssue=VCON-53)

I named the branch wrong. I called it VCON-4-Conversation-Window. It should of been VCON-53-Conversation-Window.

## How to test the PR

1. navigate to branch: `git checkout VCON-4-Conversation-Window`
2. `git pull`
3. `npm run dev`
4. Test multiple screen width.

## Things to consider

- The images are not correct as I am not sure how to get the images from Figma. 
- There is no functionality with this PR. Only HTML/CSS. 
- Everything is hard-coded in English.

2021-06-08 19:45 UTC, DaceyTom2 requested changes

2021-06-08 19:45 UTC, DaceyTom2 commented on src/components/atoms/ConversationMessage.vue
> +        isBot: Boolean,
Using the reverse of isBot as isUser might be better for reuse since it looks like we can have conversations with Jerry as well

2021-06-08 21:26 UTC, neilmispelaar commented
This looks so cool.
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Firefox 89.0 on Mac OS 10.15
Viewport:  1165 x 792 @2x
Language:  en-CA
Cookies:   Enabled
```

[View on BrowserStack](https://live.browserstack.com/dashboard#url=https%3A%2F%2Fdeploy-preview-3--vc-frontend-static-juane.netlify.app%2F&os=OS+X&os_version=Catalina&browser=Firefox&browser_version=89.0&resolution=1165x792&speed=1&start=true)



</details>

[Open Deploy Preview](https://deploy-preview-3--vc-frontend-static-juane.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=60bfbcbc61ffd00007f1d488&commentID=60bfe077ffc70300be34bcb2&resolution=resolved)

2021-06-09 14:29 UTC, DaceyTom2 approved these changes
This looks amazing

2021-06-09 14:29 UTC, merged