Vcon 221 splash page
Toad-Labs/vc-frontend-static pull request #85
Opened 2021-07-13 17:57 UTC by DaceyTom2

## [VCON-221 Create and add a splash page](https://decdvirtualconcierge.atlassian.net/browse/VCON-221?atlOrigin=eyJpIjoiYmEyZGYzMmVmZGM5NGQ0ZjhjMWQzNGI1NmQ1MjMxZWQiLCJwIjoiaiJ9)

### Description
Added splash page to root path

### Additional Notes
app layout was moved into pages to allow for splash screen
design is a mix between canada.ca and alpha with a heavier focus on canada.ca
navigation to home must be done using language /en or /fr

2021-07-14 15:07 UTC, TishamIslam requested changes
Only the bit about tailwind _needs_ to be changed. Looks really amazing so far, I can see where it's similar to canada.ca and Alpha site, but also different. I don't think it's absolutely necessary to change any/all of the following points, but I think they're important to consider and maybe discuss with Thomas or some other people:

- Alpha site has that url thing on the splash page, while canada.ca doesn't. That makes sense since Alpha isn't the main gov site. However, ours doesn't have that url identifier and I'm not sure if Alpha is supposed to be the trend here or if it's supposed to be the exception, and if the other sites (Life Journeys etc.) will follow along. Something to discuss with the other teams I think.

- The button widths for English and French are different widths on this splash page, whereas Alpha and canada.ca have the same sizes. It'd make sense to change it to fit those conventions, but isn't that big of a deal. 

- I noticed that Canada.ca has shadows on their buttons, would be cool if we could also have shadows.

2021-07-14 15:08 UTC, shewood reviewed
looks amazing.
Would there be a higher res image. this one looks quite blurry. 
Not sure about the addition of the colours. Thomas has his own choices for the VC site.

2021-07-14 15:16 UTC, shewood commented on tailwind.config.js
> +        "500px": "500px",
agreed

2021-07-14 15:21 UTC, neilmispelaar commented
This looks so amazing. 

I'm just doing a quick comparison of GCWEB and the current implementation and will get back to you with the delta.

2021-07-14 15:25 UTC, neilmispelaar commented
#### GCWEB
https://wet-boew.github.io/GCWeb/
<img width="1490" alt="Screen Shot 2021-07-14 at 11 23 06 AM" src="https://user-images.githubusercontent.com/9325038/125648228-9a15ca39-3ed7-4863-a087-d7af5cad6836.png">

#### Current implementation
<img width="1490" alt="Screen Shot 2021-07-14 at 11 23 14 AM" src="https://user-images.githubusercontent.com/9325038/125648206-ea048fb8-8a98-457b-85a2-e1d694d3a53b.png">

Background image aside (that doesn't matter) - it looks like GCWeb added:
-  a weird bottom border colour on the two buttons
- is slightly higher up on the page

Not sure if these are honestly even worth implementing - but thought I would point them out. 

Just reviewing the routes and rest of the PR now...

2021-07-14 15:28 UTC, neilmispelaar commented
Oh shoot - so sorry @TishamIslam - I'm realizing that you made literally the exact same points above. This is what happens when you don't read good.

2021-07-14 15:37 UTC, DaceyTom2 commented on tailwind.config.js
> +        "500px": "500px",
Fixed!

2021-07-14 15:37 UTC, DaceyTom2 commented on src/views/NotFound.vue
> +  <!-- skip nav component -->
I had to move the layout from app.vue but this is intentional to keep the header and footer on the 404 page

2021-07-14 15:52 UTC, DaceyTom2 commented
@TishamIslam 
I did mention to Thomas Hoy I was leaving out the alpha link and he was okay with it. Personally I am not a fan of it since it is a splash page to our page and can be skipped if language is already provided. I do agree we should probably keep as close as possible with other teams.

The buttons are updated to match sizes with Alpha and Canada.ca

Shadows have been added but tailwind shadows aren't as defined

@shewood 
The image is actually quite high res and alpha/Canada.ca/this PR adds a blur effect. I don't understand why but I followed suit...

@neilmispelaar 
Alpha has the box in the middle and canada.ca has it in a static position just below the top. Personally I like it in the middle but can change if desired

2021-07-14 16:10 UTC, neilmispelaar commented
#### Domain in box 
- I will echo that I think adding the domain to the box is silly. 

#### Position of box 
- I'm not going to lose sleep over it either way.

2021-07-14 16:11 UTC, neilmispelaar commented
Slide bug on the alpha site in mobile landscape if you are copy/pasting code

![IMG_4421](https://user-images.githubusercontent.com/9325038/125655620-3e06e72a-225d-4e0f-b371-eebbe22fe394.PNG)
![IMG_4420](https://user-images.githubusercontent.com/9325038/125655631-0108345d-2449-421d-b3cd-95faebe70083.PNG)

2021-07-14 16:18 UTC, neilmispelaar commented
Sorry - it's doing it on ours as well:

![IMG_4422](https://user-images.githubusercontent.com/9325038/125656743-688042d5-ad47-429a-82a8-931e4240a92f.PNG)

2021-07-14 16:21 UTC, neilmispelaar commented
If you do have a fix - the Alpha site could probably also benefit from it: 

https://github.com/DTS-STN/Alpha-Site/issues/191

2021-07-14 16:43 UTC, TishamIslam approved these changes
The new additions are looking great, you could change the names of the added tailwind sizes to fit the convention (would be 34.5, 75 and 125 in order of least to greatest) but aside from that , I approve.

2021-07-14 17:42 UTC, DaceyTom2 commented
@TishamIslam I was following along with Alpha naming. I'll leave it for now.

@neilmispelaar Good catch! That was tough to fix but is much nicer now

2021-07-14 17:42 UTC, merged

2021-07-15 03:41 UTC, neilmispelaar commented
Ultra small WCAG issue:

### Description

French words on the page should be identified using the `lang` attribute set to `fr`.

- There are two French words on the page
  - The French button
  - The Aviz link 
- https://www.w3.org/WAI/WCAG21/Understanding/language-of-parts.html

How to fix: 

```
<router-link
  ...
  to="/fr"
  >
  <span lang="fr">
     Français
  </span>
</router-link>
```